apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    common.k8s.elastic.co/template-hash: "2078705732"
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  name: quickstart-kb
spec:
  ports:  
  - port: 5601
    protocol: TCP
    targetPort: 5601
  type: LoadBalancer 
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
status:
  loadBalancer: {}
