apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metricName: "jvm_memory_used_bytes"
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metricName: "jvm_threads_peak"
      target:
        type: Value
        value: 500
  - type: Pods
    pods:
      metricName: "tomcat_global_request_max"
      target:
        type: Value
        value: 1000