apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 80
      nodePort: 30000
  type: NodePort
  