apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-logging
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30001
  selector:
    app: kibana
  type: NodePort
